{
  "taskDefinition": {
    "family": "test_project",
    "containerDefinitions": [
      {
        "name": "hello-world",
        "image": "396654005341.dkr.ecr.us-east-1.amazonaws.com/test_project:latest",
        "cpu": 100,
        "portMappings": [
          {
            "protocol": "tcp",
            "containerPort": 80,
            "hostPort": 80
          }
        ],
        "memory": 128,
        "essential": true
      }
    ]
  }
}